apiVersion: v1
kind: Service
metadata:
  name: sentinel-ad2usb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: ad2usb
    context: sentinel
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-ad2usb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad2usb
  template:
    metadata:
      labels:
        app: ad2usb
        context: sentinel
        version: v1
    spec:
      containers:
      -
        name: app
        image: docker.io/hashneo/sentinel-svc-ad2usb-x86_64:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: CONSUL
          value: "consul"
        - name: NEW_RELIC_NO_CONFIG_FILE
          value: "true"
        - name: NEW_RELIC_ENABLED
          value: "true"
        - name: NEW_RELIC_APP_NAME
          value: "Sentinel AD2USB"
        - name: NEW_RELIC_LICENSE_KEY
          value: ""
        ports:
        -
          containerPort: 5000
          protocol: TCP
      nodeSelector:
        beta.kubernetes.io/arch: amd64